name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-GHA-Non-Enterprise-Runner-Registration-3-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
