name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-GHA-GHEC-Approval-Workflow-Beta-2-${{ github.run_id }}-${{ github.run_attempt }}
      - deployment-status-override:true
    environment: Approvals
    steps:
      - run: echo "Hello World"
      # - run: sleep 2m
