name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-GHA-Cloud-Enterprise-Runner-Reg-IAD-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
      - run: sleep 2m
