name: Hello World
on: [push, workflow_dispatch]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-environment-permission-test-${{ github.run_id }}-${{ github.run_attempt }}
    environment: Approvals
    steps:
      - run: echo "Hello World"
      # - run: sleep 2m
